version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Leptos Development Server
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: leptos_app
  #   env_file: .env
  #   volumes:
  #     - .:/app
  #     - cargo_cache:/usr/local/cargo/registry
  #     - target_cache:/app/target
  #   ports:
  #     - "3000:3000" # App port
  #     - "3001:3001" # Hot reload port
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   stdin_open: true
  #   tty: true

volumes:
  postgres_data:
    driver: local
  # cargo_cache:
  #   driver: local
  # target_cache:
  #   driver: local
