[package]
name = "config"
version = "0.1.0"
edition = "2021"

[features]
default = []
ssr = []

[lints]
workspace = true

[dependencies]
serde.workspace = true
dotenvy.workspace = true
thiserror.workspace = true
once_cell = "1.21.3"
